### ISSUE TITLE
Support for Flatpak Steam

### ISSUE THREAD

**Issue by TiZ-HugLife** [flathub/space.crankshaft.Crankshaft#1]
Support for the Flatpak version of Steam would be great for anyone on an immutable distro like Silverblue/Kinoite, or anyone trying to keep 32-bit and/or proprietary applications away from their main distro. Thank you kindly for your work on this. :)

**Comment by coolavery** [comment]
Sorry, I wasn't watching this repo and missed this! I'm planning on improving Flatpak Steam support in the future (along with other Steam install locations), but I believe it'll still work right now if you manually set the Steam path.

You'll have to allow filesystem access to wherever your Steam directory is (using something like Flatseal or the `flatpak override` command), then launch Crankshaft with the `steam-path` flag (for example `flatpak run space.crankshaft.Crankshaft -steam-path=/home/avery/foo/bar/steam`). The specified folder should contain a folder called `steamui`.

**Comment by coolavery** [comment]
Hi, the latest release of Crankshaft should now fully support the Flatpak version of Steam without additional configuration. Please let me know if you run into problems with it!
